#!/bin/bash

PID_PATH=/tmp/haproxy.pid
BIN_PATH=/usr/sbin/haproxy
CFG_PATH=/etc/haproxy/haproxy.cfg

$BIN_PATH -f $CFG_PATH -D -p $PID_PATH

trap "$BIN_PATH -f $CFG_PATH -D -p $PID_PATH -sf \$(cat $PID_PATH)" SIGHUP
trap "kill -TERM \$(cat $PID_PATH) && exit 0" SIGTERM SIGINT